# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/osm_file.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ui_osm_file(object):
    def setupUi(self, ui_osm_file):
        ui_osm_file.setObjectName("ui_osm_file")
        ui_osm_file.resize(589, 408)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(ui_osm_file)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(ui_osm_file)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 557, 402))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.osm_file = gui.QgsFileWidget(self.scrollAreaWidgetContents)
        self.osm_file.setObjectName("osm_file")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.osm_file)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setText("Outputs")
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.radioButton_allTags = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_allTags.setChecked(True)
        self.radioButton_allTags.setObjectName("radioButton_allTags")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.radioButton_allTags)
        self.groupBox_file = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_file.setTitle("")
        self.groupBox_file.setObjectName("groupBox_file")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_file)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_file)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.output_directory = gui.QgsFileWidget(self.groupBox_file)
        self.output_directory.setObjectName("output_directory")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.output_directory)
        self.label_7 = QtWidgets.QLabel(self.groupBox_file)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_filePrefix = QtWidgets.QLineEdit(self.groupBox_file)
        self.lineEdit_filePrefix.setObjectName("lineEdit_filePrefix")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_filePrefix)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.groupBox_file)
        self.radioButton_osmConf = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_osmConf.setChecked(False)
        self.radioButton_osmConf.setObjectName("radioButton_osmConf")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.radioButton_osmConf)
        self.osm_conf = gui.QgsFileWidget(self.scrollAreaWidgetContents)
        self.osm_conf.setObjectName("osm_conf")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.osm_conf)
        self.comboBox_ouputs = CheckableOutputsComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_ouputs.sizePolicy().hasHeightForWidth())
        self.comboBox_ouputs.setSizePolicy(sizePolicy)
        self.comboBox_ouputs.setObjectName("comboBox_ouputs")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_ouputs)
        self.verticalLayout.addLayout(self.formLayout)
        self.pushButton_runQuery = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_runQuery.setObjectName("pushButton_runQuery")
        self.verticalLayout.addWidget(self.pushButton_runQuery)
        self.label_progress = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_progress.setText("text progress")
        self.label_progress.setObjectName("label_progress")
        self.verticalLayout.addWidget(self.label_progress)
        self.progressBar_execution = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        self.progressBar_execution.setProperty("value", 0)
        self.progressBar_execution.setObjectName("progressBar_execution")
        self.verticalLayout.addWidget(self.progressBar_execution)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)

        self.retranslateUi(ui_osm_file)
        self.radioButton_allTags.toggled['bool'].connect(self.groupBox_file.setEnabled)
        self.radioButton_osmConf.toggled['bool'].connect(self.osm_conf.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(ui_osm_file)
        ui_osm_file.setTabOrder(self.scrollArea, self.comboBox_ouputs)
        ui_osm_file.setTabOrder(self.comboBox_ouputs, self.radioButton_allTags)
        ui_osm_file.setTabOrder(self.radioButton_allTags, self.lineEdit_filePrefix)
        ui_osm_file.setTabOrder(self.lineEdit_filePrefix, self.radioButton_osmConf)
        ui_osm_file.setTabOrder(self.radioButton_osmConf, self.pushButton_runQuery)

    def retranslateUi(self, ui_osm_file):
        _translate = QtCore.QCoreApplication.translate
        ui_osm_file.setWindowTitle(_translate("ui_osm_file", "QuickOSM - OSM File"))
        self.label_8.setText(_translate("ui_osm_file", "<html><head/><body><p>If you have a local OSM file, you can open it using this tool. You can select which layers you want to open. QuickOSM can read all OSM keys in the file and will create new layers. Or you can provide a custom OSM configuration file. Read the <a href=\"https://www.gdal.org/drv_osm.html\"><span style=\" text-decoration: underline; color:#0000ff;\">OGR documentation</span></a> how the OSM Conf file works.</p></body></html>"))
        self.label.setText(_translate("ui_osm_file", "OSM File"))
        self.radioButton_allTags.setText(_translate("ui_osm_file", "All tags"))
        self.label_2.setText(_translate("ui_osm_file", "Directory"))
        self.label_7.setText(_translate("ui_osm_file", "File prefix"))
        self.radioButton_osmConf.setText(_translate("ui_osm_file", "OSMConf"))
        self.pushButton_runQuery.setText(_translate("ui_osm_file", "Open"))

from qgis import gui
from QuickOSM.ui.custom_widgets import CheckableOutputsComboBox
