# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/query.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ui_query(object):
    def setupUi(self, ui_query):
        ui_query.setObjectName("ui_query")
        ui_query.resize(603, 871)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(ui_query)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(ui_query)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 585, 853))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.horizontalLayout_9.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Reset)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_9.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.textEdit_query = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.textEdit_query.setAcceptRichText(False)
        self.textEdit_query.setObjectName("textEdit_query")
        self.verticalLayout.addWidget(self.textEdit_query)
        self.advanced = gui.QgsCollapsibleGroupBox(self.scrollAreaWidgetContents)
        self.advanced.setChecked(False)
        self.advanced.setObjectName("advanced")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.advanced)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_2 = QtWidgets.QLabel(self.advanced)
        self.label_2.setText("{{geocodeArea:}}")
        self.label_2.setObjectName("label_2")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_nominatim = QtWidgets.QLineEdit(self.advanced)
        self.lineEdit_nominatim.setObjectName("lineEdit_nominatim")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_nominatim)
        self.label_5 = QtWidgets.QLabel(self.advanced)
        self.label_5.setObjectName("label_5")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cb_query_type = QtWidgets.QComboBox(self.advanced)
        self.cb_query_type.setObjectName("cb_query_type")
        self.horizontalLayout_3.addWidget(self.cb_query_type)
        self.comboBox_extentLayer = gui.QgsMapLayerComboBox(self.advanced)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_extentLayer.sizePolicy().hasHeightForWidth())
        self.comboBox_extentLayer.setSizePolicy(sizePolicy)
        self.comboBox_extentLayer.setObjectName("comboBox_extentLayer")
        self.horizontalLayout_3.addWidget(self.comboBox_extentLayer)
        self.formLayout_4.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_3 = QtWidgets.QLabel(self.advanced)
        self.label_3.setObjectName("label_3")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.comboBox_outputs = CheckableOutputsComboBox(self.advanced)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_outputs.sizePolicy().hasHeightForWidth())
        self.comboBox_outputs.setSizePolicy(sizePolicy)
        self.comboBox_outputs.setObjectName("comboBox_outputs")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_outputs)
        self.verticalLayout_2.addLayout(self.formLayout_4)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(self.advanced)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.output_directory = gui.QgsFileWidget(self.advanced)
        self.output_directory.setObjectName("output_directory")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.output_directory)
        self.label_6 = QtWidgets.QLabel(self.advanced)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_filePrefix = QtWidgets.QLineEdit(self.advanced)
        self.lineEdit_filePrefix.setObjectName("lineEdit_filePrefix")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_filePrefix)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.verticalLayout.addWidget(self.advanced)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_generateQuery = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_generateQuery.setObjectName("pushButton_generateQuery")
        self.horizontalLayout_2.addWidget(self.pushButton_generateQuery)
        self.pushButton_runQuery = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_runQuery.setDefault(True)
        self.pushButton_runQuery.setObjectName("pushButton_runQuery")
        self.horizontalLayout_2.addWidget(self.pushButton_runQuery)
        self.pushButton_saveQuery = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_saveQuery.setObjectName("pushButton_saveQuery")
        self.horizontalLayout_2.addWidget(self.pushButton_saveQuery)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_progress = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_progress.sizePolicy().hasHeightForWidth())
        self.label_progress.setSizePolicy(sizePolicy)
        self.label_progress.setText("progress text")
        self.label_progress.setObjectName("label_progress")
        self.verticalLayout.addWidget(self.label_progress)
        self.progressBar_execution = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        self.progressBar_execution.setProperty("value", 0)
        self.progressBar_execution.setObjectName("progressBar_execution")
        self.verticalLayout.addWidget(self.progressBar_execution)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_overpassTurbo = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_overpassTurbo.setText("Overpass Turbo")
        self.pushButton_overpassTurbo.setObjectName("pushButton_overpassTurbo")
        self.horizontalLayout_5.addWidget(self.pushButton_overpassTurbo)
        self.pushButton_documentation = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_documentation.setObjectName("pushButton_documentation")
        self.horizontalLayout_5.addWidget(self.pushButton_documentation)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 71, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)

        self.retranslateUi(ui_query)
        QtCore.QMetaObject.connectSlotsByName(ui_query)
        ui_query.setTabOrder(self.scrollArea, self.textEdit_query)
        ui_query.setTabOrder(self.textEdit_query, self.advanced)
        ui_query.setTabOrder(self.advanced, self.lineEdit_nominatim)
        ui_query.setTabOrder(self.lineEdit_nominatim, self.cb_query_type)
        ui_query.setTabOrder(self.cb_query_type, self.comboBox_extentLayer)
        ui_query.setTabOrder(self.comboBox_extentLayer, self.comboBox_outputs)
        ui_query.setTabOrder(self.comboBox_outputs, self.lineEdit_filePrefix)
        ui_query.setTabOrder(self.lineEdit_filePrefix, self.pushButton_generateQuery)
        ui_query.setTabOrder(self.pushButton_generateQuery, self.pushButton_runQuery)
        ui_query.setTabOrder(self.pushButton_runQuery, self.pushButton_saveQuery)
        ui_query.setTabOrder(self.pushButton_saveQuery, self.pushButton_overpassTurbo)
        ui_query.setTabOrder(self.pushButton_overpassTurbo, self.pushButton_documentation)

    def retranslateUi(self, ui_query):
        _translate = QtCore.QCoreApplication.translate
        ui_query.setWindowTitle(_translate("ui_query", "QuickOSM - Query"))
        self.label.setText(_translate("ui_query", "Overpass query"))
        self.advanced.setTitle(_translate("ui_query", "Advanced"))
        self.lineEdit_nominatim.setPlaceholderText(_translate("ui_query", "Can be overridden"))
        self.label_5.setText(_translate("ui_query", "{{bbox}} or {{center}}"))
        self.label_3.setText(_translate("ui_query", "Outputs"))
        self.label_4.setText(_translate("ui_query", "Directory"))
        self.label_6.setText(_translate("ui_query", "File prefix"))
        self.pushButton_generateQuery.setText(_translate("ui_query", "Generate query"))
        self.pushButton_runQuery.setText(_translate("ui_query", "Run query"))
        self.pushButton_saveQuery.setText(_translate("ui_query", "Save query"))
        self.pushButton_documentation.setText(_translate("ui_query", "Documentation"))

from qgis import gui
from QuickOSM.ui.custom_widgets import CheckableOutputsComboBox
