# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/quick_query.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ui_quick_query(object):
    def setupUi(self, ui_quick_query):
        ui_quick_query.setObjectName("ui_quick_query")
        ui_quick_query.resize(644, 805)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(ui_quick_query)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(ui_quick_query)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 626, 787))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_mapFeatures = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_mapFeatures.setObjectName("pushButton_mapFeatures")
        self.horizontalLayout_4.addWidget(self.pushButton_mapFeatures)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Reset)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_4.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.comboBox_key = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_key.sizePolicy().hasHeightForWidth())
        self.comboBox_key.setSizePolicy(sizePolicy)
        self.comboBox_key.setEditable(True)
        self.comboBox_key.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_key.setObjectName("comboBox_key")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_key)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.comboBox_value = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_value.sizePolicy().hasHeightForWidth())
        self.comboBox_value.setSizePolicy(sizePolicy)
        self.comboBox_value.setEditable(True)
        self.comboBox_value.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_value.setObjectName("comboBox_value")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_value)
        self.cb_query_type = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.cb_query_type.setObjectName("cb_query_type")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.cb_query_type)
        self.stacked_query_type = QtWidgets.QStackedWidget(self.scrollAreaWidgetContents)
        self.stacked_query_type.setLineWidth(0)
        self.stacked_query_type.setObjectName("stacked_query_type")
        self.nominatim = QtWidgets.QWidget()
        self.nominatim.setObjectName("nominatim")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.nominatim)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit_nominatim = QtWidgets.QLineEdit(self.nominatim)
        self.lineEdit_nominatim.setObjectName("lineEdit_nominatim")
        self.horizontalLayout_6.addWidget(self.lineEdit_nominatim)
        self.spinBox_distance_point = QtWidgets.QSpinBox(self.nominatim)
        self.spinBox_distance_point.setPrefix("")
        self.spinBox_distance_point.setMinimum(1)
        self.spinBox_distance_point.setMaximum(999999999)
        self.spinBox_distance_point.setSingleStep(100)
        self.spinBox_distance_point.setProperty("value", 1000)
        self.spinBox_distance_point.setObjectName("spinBox_distance_point")
        self.horizontalLayout_6.addWidget(self.spinBox_distance_point)
        self.stacked_query_type.addWidget(self.nominatim)
        self.layerExtent = QtWidgets.QWidget()
        self.layerExtent.setObjectName("layerExtent")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layerExtent)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.comboBox_extentLayer = gui.QgsMapLayerComboBox(self.layerExtent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_extentLayer.sizePolicy().hasHeightForWidth())
        self.comboBox_extentLayer.setSizePolicy(sizePolicy)
        self.comboBox_extentLayer.setObjectName("comboBox_extentLayer")
        self.horizontalLayout_7.addWidget(self.comboBox_extentLayer)
        self.stacked_query_type.addWidget(self.layerExtent)
        self.nothingDisplayed = QtWidgets.QWidget()
        self.nothingDisplayed.setObjectName("nothingDisplayed")
        self.stacked_query_type.addWidget(self.nothingDisplayed)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.stacked_query_type)
        self.verticalLayout.addLayout(self.formLayout)
        self.advanced = gui.QgsCollapsibleGroupBox(self.scrollAreaWidgetContents)
        self.advanced.setChecked(False)
        self.advanced.setObjectName("advanced")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.advanced)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtWidgets.QLabel(self.advanced)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.spinBox_timeout = QtWidgets.QSpinBox(self.advanced)
        self.spinBox_timeout.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_timeout.setMinimum(25)
        self.spinBox_timeout.setMaximum(2000)
        self.spinBox_timeout.setSingleStep(25)
        self.spinBox_timeout.setObjectName("spinBox_timeout")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBox_timeout)
        self.label_4 = QtWidgets.QLabel(self.advanced)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.output_directory = gui.QgsFileWidget(self.advanced)
        self.output_directory.setObjectName("output_directory")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.output_directory)
        self.label_6 = QtWidgets.QLabel(self.advanced)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_filePrefix = QtWidgets.QLineEdit(self.advanced)
        self.lineEdit_filePrefix.setObjectName("lineEdit_filePrefix")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_filePrefix)
        self.label_3 = QtWidgets.QLabel(self.advanced)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_13 = QtWidgets.QLabel(self.advanced)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.comboBox_outputs = CheckableOutputsComboBox(self.advanced)
        self.comboBox_outputs.setObjectName("comboBox_outputs")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_outputs)
        self.comboBox_osm_objects = CheckableOsmObjectsComboBox(self.advanced)
        self.comboBox_osm_objects.setObjectName("comboBox_osm_objects")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_osm_objects)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.verticalLayout.addWidget(self.advanced)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_showQuery = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_showQuery.setObjectName("pushButton_showQuery")
        self.horizontalLayout_2.addWidget(self.pushButton_showQuery)
        self.pushButton_runQuery = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_runQuery.setDefault(True)
        self.pushButton_runQuery.setObjectName("pushButton_runQuery")
        self.horizontalLayout_2.addWidget(self.pushButton_runQuery)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_progress = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_progress.sizePolicy().hasHeightForWidth())
        self.label_progress.setSizePolicy(sizePolicy)
        self.label_progress.setText("progress text")
        self.label_progress.setObjectName("label_progress")
        self.verticalLayout.addWidget(self.label_progress)
        self.progressBar_execution = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        self.progressBar_execution.setProperty("value", 0)
        self.progressBar_execution.setObjectName("progressBar_execution")
        self.verticalLayout.addWidget(self.progressBar_execution)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)

        self.retranslateUi(ui_quick_query)
        self.stacked_query_type.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ui_quick_query)
        ui_quick_query.setTabOrder(self.scrollArea, self.pushButton_mapFeatures)
        ui_quick_query.setTabOrder(self.pushButton_mapFeatures, self.comboBox_key)
        ui_quick_query.setTabOrder(self.comboBox_key, self.comboBox_value)
        ui_quick_query.setTabOrder(self.comboBox_value, self.cb_query_type)
        ui_quick_query.setTabOrder(self.cb_query_type, self.lineEdit_nominatim)
        ui_quick_query.setTabOrder(self.lineEdit_nominatim, self.spinBox_distance_point)
        ui_quick_query.setTabOrder(self.spinBox_distance_point, self.advanced)
        ui_quick_query.setTabOrder(self.advanced, self.comboBox_osm_objects)
        ui_quick_query.setTabOrder(self.comboBox_osm_objects, self.comboBox_outputs)
        ui_quick_query.setTabOrder(self.comboBox_outputs, self.spinBox_timeout)
        ui_quick_query.setTabOrder(self.spinBox_timeout, self.lineEdit_filePrefix)
        ui_quick_query.setTabOrder(self.lineEdit_filePrefix, self.pushButton_showQuery)
        ui_quick_query.setTabOrder(self.pushButton_showQuery, self.pushButton_runQuery)
        ui_quick_query.setTabOrder(self.pushButton_runQuery, self.comboBox_extentLayer)

    def retranslateUi(self, ui_quick_query):
        _translate = QtCore.QCoreApplication.translate
        ui_quick_query.setWindowTitle(_translate("ui_quick_query", "QuickOSM - Quick query"))
        self.pushButton_mapFeatures.setText(_translate("ui_quick_query", "Help with key/value"))
        self.label.setToolTip(_translate("ui_quick_query", "An OSM key to fetch. If empty, all keys will be fetched."))
        self.label.setText(_translate("ui_quick_query", "Key"))
        self.comboBox_key.setToolTip(_translate("ui_quick_query", "An OSM key to fetch. If empty, all keys will be fetched."))
        self.label_2.setToolTip(_translate("ui_quick_query", "An OSM value to fetch. If empty, all values will be fetched."))
        self.label_2.setText(_translate("ui_quick_query", "Value"))
        self.comboBox_value.setToolTip(_translate("ui_quick_query", "An OSM value to fetch. If empty, all values will be fetched."))
        self.cb_query_type.setToolTip(_translate("ui_quick_query", "The spatial extent to use for the query."))
        self.lineEdit_nominatim.setPlaceholderText(_translate("ui_quick_query", "A village, a town, ..."))
        self.spinBox_distance_point.setSuffix(_translate("ui_quick_query", "m"))
        self.advanced.setTitle(_translate("ui_quick_query", "Advanced"))
        self.label_5.setText(_translate("ui_quick_query", "Timeout"))
        self.label_4.setText(_translate("ui_quick_query", "Directory"))
        self.label_6.setText(_translate("ui_quick_query", "File prefix"))
        self.label_3.setText(_translate("ui_quick_query", "OSM objects"))
        self.label_13.setText(_translate("ui_quick_query", "Outputs"))
        self.pushButton_showQuery.setText(_translate("ui_quick_query", "Show query"))
        self.pushButton_runQuery.setText(_translate("ui_quick_query", "Run query"))

from qgis import gui
from QuickOSM.ui.custom_widgets import CheckableOsmObjectsComboBox, CheckableOutputsComboBox
